### ISSUE TITLE
投票状況の表示

### ISSUE THREAD

**Issue by shutaro21** [shutaro21/game#1]
経過中画面で、自分の投票内容、他人の投票状況を表示する。

**Comment by satoruinage** [comment]
経過中の画面では他人の投票状況(ペア予想)は見えないのが原版のルールになっています。
なので、自分の投票状況(ペア予想)だけは見えておいた方が良いかと思います。

**Comment by shutaro21** [comment]
他人分は、投票内容ではなく、投票したか投票していないか、という表示を想定していましたが
それがわからないということでしょうか。

| プレイヤー | 投票１ | 投票 2 |
| ------------- | ------------- | ------------- |
| Aさん | 投票済み | 未投票  |
| Bさん | 投票済み  | 投票済み  |
| 自分 | 投票済み  | AさんーBさん  |

**Comment by satoruinage** [comment]
理解しました。こちらで良いかと思います。
自分の投票済みのペア予想内容は、1回目投票以降でも表示されるような仕様だとより原版(アナログ)に近いと思います。

**Comment by shutaro21** [comment]
> 自分の投票済みのペア予想内容は、1回目投票以降でも表示されるような仕様だとより原版(アナログ)に近いと思います。

あ、間違えてました。そのイメージです。
