### ISSUE TITLE
偶数プレイヤーの場合の？陣営の実装

### ISSUE THREAD

**Issue by satoruinage** [shutaro21/game#4]
原版のルールをよく確認したら、偶数人数でのプレイの場合、？陣営が2人いるようですのでこれを実装いただければと。

この場合の？陣営は、？プレイヤー2人がペアであると言う事では無く、通常の？陣営と同じ扱いになります。

例えば、6人でのプレイの場合のプレイヤーの内訳は以下のようになります。
A1、A2、B1、B2、？1、？2

？陣営のプレイヤーが誰かのペア予想に登場したら、その人から点をいただくのがルールに変わりはありません。
上記の例の場合、A1のペア予想が「A1-A2」と「？1-？2」であった場合、A1から？1と？2へ1点ずつ点を渡すことになります。また、？1が「A1-？2」と言うような予想をしていた場合は、？1は？2へ1点渡すことになります。

**Comment by shutaro21** [comment]
ちなみにA1のペア予想が「A1-？1」と「A2-？1」だった場合は、
A1から？1へ2点を渡す、であってますか？

**Comment by satoruinage** [comment]
Webを探ってみた限りでは認識の通りでOKかと思います。
