### ISSUE TITLE
現在の発言者表示機能の実装

### ISSUE THREAD

**Issue by satoruinage** [shutaro21/game#5]
今誰がヒントを書き込んで(悩んで)いるかがわかるようになるとやりやすいと思います。

**Comment by shutaro21** [comment]
ゲーム開始後は、プレイヤーはヒントを出す順番（ランダム決定）に並んでいて、
上から順番にヒントが埋まっていくので誰がヒントの番かわかると思いますが
それでは不足でしょうか？
5秒のポーリングの時差は、今の実装では埋められません。（秒数を短くすることは可能ですが。）

Zoomを使用している場合は入力と合わせて発声してもいいかもしれません。

**Comment by satoruinage** [comment]
一見誰が書き込んでいるかが分かり難いので、アクティブプレイヤーの色を変えるとかするとわかりやすいかなと。
理想としては、自分以外がアクティブプレイヤーの場合は、一覧においてその人の行の色が変わる。自分がアクティブプレイヤーの場合は、Web画面のバックの色が変わるとかなるとわかりやすいかも。
